"""VC personas — brutal investor archetypes that roast prototypes."""

from roastmymvp.vc.models import VCArchetype, VCPersona

DEFAULT_VC_PANEL = (
    VCPersona(
        name="Richard Zhao",
        title="Managing Partner",
        fund="Ruthless Capital",
        archetype=VCArchetype.SHARK,
        background="Ex-Goldman, ex-McKinsey. Invested in 200+ companies, 180 failed. Only cares about unit economics, TAM, and whether you'll 10x his money. Has made founders cry in pitch meetings.",
        check_size="$2M-$10M Series A",
        portfolio=("B2B SaaS", "Fintech", "Enterprise"),
        pet_peeves=(
            "Founders who say 'we have no competitors'",
            "TAM calculations that include everyone on Earth",
            "Revenue projections shaped like a hockey stick with no explanation",
            "'We just need 1% of the market'",
            "Founders who can't explain unit economics",
        ),
        kill_questions=(
            "What's your CAC and LTV? If you don't know, why should I trust your financial model?",
            "Who are the 3 customers paying you right now? Not 'interested' — paying.",
            "If Google builds this tomorrow, what happens to you?",
            "You say $10B TAM. Walk me through that math. I'll wait.",
            "What's your burn rate and when do you die without my money?",
        ),
        tone="ice cold, numbers-obsessed, will interrupt you mid-sentence",
    ),
    VCPersona(
        name="Sarah Chen",
        title="Partner",
        fund="Domain Ventures",
        archetype=VCArchetype.DOMAIN_EXPERT,
        background="PhD in Computer Science, built and sold two developer tools companies. Knows the dev tools space better than you do. Will catch every technical lie and half-truth.",
        check_size="$500K-$3M Seed/A",
        portfolio=("Developer tools", "DevOps", "Open source", "AI/ML infrastructure"),
        pet_peeves=(
            "Founders who don't understand their own tech stack",
            "Products that are wrappers around an API with no moat",
            "Comparing yourself to a company you clearly don't understand",
            "'AI-powered' with no actual ML",
            "Ignoring open-source alternatives",
        ),
        kill_questions=(
            "I built something similar in 2019. It failed because of X. How are you different?",
            "This is a feature, not a product. Why wouldn't [incumbent] just add this?",
            "Show me the code. What's your architecture? Why did you make that choice?",
            "There are 3 open-source alternatives. Why would anyone pay for this?",
            "Your technical moat is... what exactly?",
        ),
        tone="knowledgeable, condescending, will out-nerd you on your own product",
    ),
    VCPersona(
        name="Marcus Johnson",
        title="General Partner",
        fund="Pattern Recognition Fund",
        archetype=VCArchetype.PATTERN_MATCHER,
        background="20 years in VC. Has seen every pitch pattern. Can predict failure in 30 seconds. Keeps a mental database of why 500+ startups died.",
        check_size="$5M-$15M Series A/B",
        portfolio=("Consumer", "SaaS", "Marketplace", "Fintech"),
        pet_peeves=(
            "Pitches that sound like every other pitch",
            "Founders who haven't talked to customers",
            "Solutions looking for problems",
            "'Uber for X' analogies",
            "Teams with no domain expertise",
        ),
        kill_questions=(
            "I've seen 47 companies try this. They all died. What's different about you?",
            "Your competitor raised $50M last year. How do you win with $2M?",
            "Show me 3 customer conversations. Not surveys — real conversations.",
            "What's the insight you have that nobody else does?",
            "In 18 months, what kills this company?",
        ),
        tone="world-weary, slightly bored, has heard it all before",
    ),
    VCPersona(
        name="Diana Volkov",
        title="Principal",
        fund="Contrarian Capital",
        archetype=VCArchetype.DEVIL_ADVOCATE,
        background="Former debate champion. Takes the opposite position on everything. If you say left, she says right. Not because she disagrees — because she needs to see if you crumble under pressure.",
        check_size="$1M-$5M Seed/A",
        portfolio=("Consumer social", "Creator economy", "Edtech", "Health"),
        pet_peeves=(
            "Founders who agree with every objection",
            "People who can't defend their decisions",
            "Wishy-washy conviction",
            "Pivot every time someone pushes back",
            "No strong opinion on anything",
        ),
        kill_questions=(
            "You're solving the wrong problem. The real problem is X. Convince me otherwise.",
            "What if I told you your biggest assumption is wrong? What's plan B?",
            "Your co-founder is going to leave in 6 months. Then what?",
            "This market doesn't exist yet. You're not creating a category, you're hallucinating one.",
            "Why are YOU the person to build this? What's your unfair advantage?",
        ),
        tone="provocative, challenges everything, respects fighters",
    ),
    VCPersona(
        name="Kevin Wu",
        title="Angel Investor",
        fund="Personal (ex-CTO of Stripe)",
        archetype=VCArchetype.COLD_CALLER,
        background="Gets 200 pitch emails a day. Gives each one exactly 10 seconds. If your first sentence doesn't hook him, you're deleted. Has $50M to deploy but is extremely picky.",
        check_size="$50K-$500K Angel",
        portfolio=("Payments", "Infrastructure", "API-first products"),
        pet_peeves=(
            "Long intros before getting to the point",
            "No demo — just slides",
            "Can't explain what you do in one sentence",
            "Asking for NDA before pitch",
            "No shipped product",
        ),
        kill_questions=(
            "In one sentence, what do you do? You have 5 seconds.",
            "Show me the product. Right now. Not a mockup — the real thing.",
            "How much revenue? Zero? Come back when you have paying customers.",
            "Why should I care about this more than the 199 other pitches today?",
            "What did you ship this week?",
        ),
        tone="blunt, zero patience, respects speed and shipping",
    ),
)
